---
- name: Correct the mistakes
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
  - name: Create user student_new
    user:
      name: student_new
      state: present
    
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
      
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
      
  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
      
  - name: print rhel version
    debug:
      msg: "The distribution of this server is RED HAT 8.7"
    when: ansible_facts.distribution == "REDHAT" and ansible_facts.distribution-version == "8.7"
    
  - name: Create template with user input from survey
    template:
      src: template.j2
      dest: /tmp/template
